### ISSUE TITLE
datalab is only accessible first time after creating cluster

### ISSUE THREAD

**Issue by adam2326** [GoogleCloudPlatform/dataproc-initialization-actions#125]
I create a cluster and utilize the dataproc-initialization-actions script for datalab (gs://dataproc-initialization-actions/datalab/datalab.sh).

then use the [cluster web interfaces instructions](https://cloud.google.com/dataproc/docs/concepts/cluster-web-interfaces) to create a connection.  datalab is accessible to me at  http://master-host-name:8080/tree/datalab.  I can utilize Spark etc. from the datalab notebook.

If I stop the cluster nodes in Compute Engine -> Instances, then restart the nodes, I can no longer navigate to http://master-host-name:8080/tree/datalab.  I have tried multiple times with multiple clusters.  The YARN UI is always accessible.

Is this expected?

**Comment by karth295** [comment]
This is an oversight on our part -- good catch. We configure a systemd service for all the core services and most of the init actions in this repo, so they start when the node reboots -- that's why the YARN UI is accessible on reboot.

Since the Datalab init action is run through docker rather than systemd, there is a docker-native method to restarting docker containers: https://docs.docker.com/engine/admin/start-containers-automatically/

We should probably add `--restart always` to the `docker run` command. Feel free to send a PR adding that. Otherwise, I'll get to adding (and testing) that next week.
