### ISSUE TITLE
Question: apply custom Docker image to Dataproc cluster nodes?

### ISSUE THREAD

**Issue by sooheelee** [GoogleCloudPlatform/dataproc-initialization-actions#127]
I have a Docker image with the settings and software I need. Is it possible for Dataproc to use the image during cluster generation? I cannot seem to find related documentation.

I see in https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/datalab/datalab.sh that cluster generation pulls from a docker image with
```
gcloud docker -- pull ${DOCKER_IMAGE}
```
where
```
  DOCKER_IMAGE="gcr.io/cloud-datalab/datalab:local"
```
If I use this command to point to my own docker image in a custom script, and supply this to `Initialization actions` in cluster generation, will this work?

Thanks in advance for your help. Please let me know if I should be posting questions elsewhere.

**Comment by pmkc** [comment]
You're welcome to try, but it might not work.

The main assumption on the docker image is that it is based on Debian 8 Jessie otherwise [this safeguard](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/8f3bd6c/datalab/datalab.sh#L68) will fail. The assumption is necessary to install Java 8 and Spark consistently with dataproc. You could try to bring your own image with Spark inside, but I would get rid of the Dockerfile portion and just `docker run FLAGS $DOCKER_IMAGE` [here](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/8f3bd6c/datalab/datalab.sh#L91).

I once tried to use it with https://github.com/jupyter/docker-stacks, but never quite got it to work.
