### ISSUE TITLE
Hue and Oozie: User [hue] not defined as proxyuser

### ISSUE THREAD

**Issue by britishbadger** [GoogleCloudPlatform/dataproc-initialization-actions#157]
Hi, I've deployed hue and oozie into a new dataproc cluster but get the following error in Hue when clicking on the workflows dropdown: 

_User [hue] not defined as proxyuser_

Does anyone know how to remedy the issue?

**Comment by mikaylakonst** [comment]
My first guess would be that you need to make sure to run the oozie init action before the hue init action, because the hue init action checks if oozie is installed before adding hue as a proxy user:

https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/5d9ddd111f59cd481ea524755493bf5f86438c0b/hue/hue.sh#L71

Also, the fix that added hue as a proxy user was recent, so I would try at HEAD.

**Comment by britishbadger** [comment]
Thanks, I will give this a go. Is this already in the gcs bucket or would you recommend cloning and pushing this into bucket before initializing the cluster?

**Comment by pmkc** [comment]
I double checked and `gs://dataproc-initialization-actions` is up-to-date.

**Comment by britishbadger** [comment]
Re-created the cluster and that has resolved the issue. Thanks
