### ISSUE TITLE
Apache Tez not working on HA mode

### ISSUE THREAD

**Issue by szewi** [GoogleCloudPlatform/dataproc-initialization-actions#199]
The initialization action fails for apache tez in HA mode, with an multiple errors of:
> copyFromLocal: `/apps/tez/hadoop-shim-0.8.4.jar': File exists
> copyFromLocal: `/apps/tez/hadoop-shim-2.8-0.8.4.jar': File exists

Problem is connected with copying of tez jar files to ${tez_hdfs_path} by each of master nodes. 
`hadoop fs -copyFromLocal ${tez_jars}/* ${tez_hdfs_path}/
` when second master is trying to copy jar files they are already there.

Sometimes additionally following errors occur, but they are all related to this issue:
>copyFromLocal: File does not exist: /apps/tez/tez-yarn-timeline-history-with-acls.jar._COPYING_ (inode 16549) Holder DFSClient_NONMAPREDUCE_-1172794459_1
>copyFromLocal: File does not exist: /apps/tez/tez-yarn-timeline-history-with-fs-0.8.4.jar._COPYING_`

Steps to reproduce:
`gcloud dataproc clusters create tez-kamil --initialization-actions gs://dataproc-initialization-actions/tez/tez.sh --initialization-action-timeout 5m --num-workers 2 --num-masters 3 --worker-machine-type n1-standard-4 --master-machine-type n1-standard-4
`

Using `hadoop fs -copyFromLocal -f` that forces write operation seem to help, but doesn't solve the issue with HA mode.

**Comment by karth295** [comment]
So the reason this happens is that `hadoop fs -copyFromLocal` writes a temp file, then renames to the final location. It does this so that if you fail writing a file halfway, you never write the final file (but just leave a temp file around). The problem here is that it always uses the same temp file. There's a race condition where 2 writers overwrite the same temp file, 1 writers succeeds in renaming it, and the 2nd writer complains that the file is not found.

One reasonable solution is to only run this code if `$HOSTNAME == dataproc-master` (aka -m-0), and put a comment explaining why that's necessary.

**Comment by szewi** [comment]
Thx @karth295 I was also thinking about doing `hadoop fs -test` on  `${tez_hdfs_path}`, but this seem to be a simple solution. I tested your proposal and ended up with known issue about hive2.server  on multiple masters. I fixed both. I will submit a PR and you will see.
