### ISSUE TITLE
ipython kernel busy

### ISSUE THREAD

**Issue by tuanavu** [GoogleCloudPlatform/dataproc-initialization-actions#24]
After initializing the ipython.sh into the cluster, the ipython notebook always seem to be busy. What is the issue behind this?

**Comment by nehalecky** [comment]
Hi @tuanvu216, I've also encountered the same issue, and it typically happens when one tries to open a second notebook. I haven't confirmed exactly why this is, however, I suspect that it's due to the way the IPython init action is configured to instantiate a `SparkContext`, and in particular the port settings.

See more, [StackOverflow: Start multiple SparkContext Instances in Ipython](http://stackoverflow.com/questions/31314645/start-multiple-sparkcontext-instances-in-ipython). Are you able to check any logs?

**Comment by tuanvu216** [comment]
Hi @nehalecky,

This is what I see in the Spark cluster:

![image](https://cloud.githubusercontent.com/assets/6547031/12436400/cc4aa006-bec9-11e5-9264-81a22935e88c.png)

As you can see the UNDEFINED indicates the notebook that has busy kernel. Checking it, this is what I see:

![image](https://cloud.githubusercontent.com/assets/6547031/12436432/1ce84aae-beca-11e5-8eb2-135edfb5722d.png)

**Comment by karth295** [comment]
For posterity: you can only have a limited number of applications running concurrently -- specified as a fraction of the cluster size. See `yarn.scheduler.capacity.maximum-applications` and `yarn.scheduler.capacity.maximum-am-resource-percent`. We set max applications to 10000 (virtually infinite), and max percentage of app master resources to 25% of the cluster.

The latter means that the number of applications you can run concurrently is limited to the size of your cluster. You likely don't want to increase that percentage -- the other 75% is used for executors (or map/reduce containers when running MapReduce jobs).
