### ISSUE TITLE
[Cloud SQL Proxy] Encrypt/decrypt passwords with KMS

### ISSUE THREAD

**Issue by jphalip** [GoogleCloudPlatform/dataproc-initialization-actions#256]
Currently the MySQL root password and hive user password are hardcoded in the script, which isn't very secure.

I suggest we update the script to fetch those secrets from a GCS bucket and decrypt them using keys stored in KMS.

If you agree, then I'm happy to write a patch for it. I should be able to keep it backwards-compatible to avoid breaking existing code.

**Comment by functicons** [comment]
GCS + KMS sounds good to me.

**Comment by jphalip** [comment]
Ok great, I'll work on a patch.

**Comment by karth295** [comment]
Here's my (uninformed) train of thought. Disclaimer: we should talk to @AngusDavis , @bsidhom , @dennishuo who know a lot more about security. 

These init actions are intended to be examples (starting points). Most of them are good enough for "Hello, world", but you will likely need to customize them to fit your needs. In general, you should copy these scripts to your own GCS bucket. This also ensures that breaking changes to these examples do not break your pipelines.

So the current way to specify a password is to copy the script into your own GCS bucket and hardcode the password.

* Security
  * GCS ACLs (IAM?)
* Pros
  * No changes required (for dataproc)
* Cons
  * Users need to fork the script.

Alright, so I'll go down the thought experiment of this proposal. If we don't want to fork the script, there needs to be a way to specify the `root` and `hive` user passwords. My first thought is metadata keys.

* Security
  * Need to secure whatever script is running `gcloud dataproc clusters create`, since it will include the password
  * Dataproc IAM (metadata shows up in `gcloud dataproc clusters describe`
  * GCE IAM (metadata shows up in all instances in `gcloud compute instances describe`
* Pros
  * No extra dependencies
  * In line with how the other init actions work (see Jupyter's AUTH_TOKEN).
* Cons
  * For security-conscious users, this could be more work than forking the script.

This issue suggests KMS + encrypted password in GCS.

* Security
  * KMS
* Pros
  * KMS has nice security features like revoking keys
* Cons
  * Adds complexity -- you need a GCS file for each user and at least one KMS key
  * You have to specify the password in plaintext to Cloud SQL when creating the instance or creating users. You can't give it this KMS key + GCS file

In addition, we need to remember that any user that can `ssh` to a Dataproc cluster has `root` access, meaning they can read any file on the VM and view the arguments passed to any process. So in other words, I think any user that can `ssh` can see the passwords. Also, any user with permission to change user passwords in Cloud SQL can do so.

I'm not trying to discourage you from writing this patch, but I'm not yet convinced that this complexity is significantly better than just hardcoding the password in your version of the script. For example, isn't changing the password in Cloud SQL just as good as revoking a key in KMS?

**Comment by jphalip** [comment]
@karth295 Thanks for the thorough feedback. You raise some great questions and I understand your reservations.

I agree that the init actions presented in this repository should be considered as starting points, as it's unlikely that they would cover every possible use case that one might need in a large production setup. That said, they're also an opportunity to show some recommended patterns and best practices wherever possible. So yes it's true, it's just a matter of finding the right balance between over-simplification and over-complication :)

To answer your question ("isn't changing the password in Cloud SQL just as good as revoking a key in KMS?"). These would indeed have essentially the same effect. However, my original motivation here was to remove any passwords from the code, so that you could then check that code into a source repository.

When you say that "any user that can ssh to a Dataproc cluster has root access", could you clarify exactly what that means and how this happens? Also, could that perhaps be prevented by using [OS Login](https://cloud.google.com/compute/docs/instances/managing-instance-access)?

Regarding the option of passing passwords directly as metadata values, I would be wary of that as the passwords would then be logged in the command history when creating the cluster (and possibly also in HTTP logs?).

Maybe if I take a step back, I think that ideally the goals that would be great to achieve are:
- Make it acceptable to check an init action's code into a source repository, i.e. free of any passwords.
- Prevent any passwords from being logged anywhere (command history, HTTP logs, etc.).
- Prevent non-sudo users to access to the passwords stored on the VM's disk.
- Make it as easy as possible to reset passwords (or revoke keys) with minimal disruption.

I'll think a bit more about it. Any further feedback welcome. Thanks!

**Comment by karth295** [comment]
Ah, thanks for the detailed response. I didn't even consider checking in init actions into a repository -- that's an excellent reason for this proposal. It's great to have an outsider perspective :)

You only need to worry about security on the cluster if there are users that should not have access as `root` to the particular cloud sql instance(s). If that's the case, could we write a script that does not need to authenticate as `root` to Cloud SQL, but instead just as a user with appropriate access? (I assume if you don't need to create a user you don't need to auth as `root`).

That's generally the principle Dataproc follows -- the cluster has an identity, and any user that can `ssh` or submit jobs to the cluster can act as that identity. This is how we recommend users securely run jobs against data in GCS or BQ -- create a cluster per job, or at least a cluster per identity.

But to directly answer your question: OS Login sounds possible. In addition, I believe most Dataproc job types run drivers as `root`. So you would need to disable Dataproc job submission for unprivileged users: https://cloud.google.com/dataproc/docs/concepts/iam/granular-iam. But this is pretty difficult.

**Comment by jphalip** [comment]
So I've got a working patch that should be backwards compatible: https://github.com/jphalip/dataproc-initialization-actions/compare/c402333a7837bc12c6a2617b0f2effb084287332...jphalip:cloud-sql-proxy-kms

The patch also makes it work without the MySQL `root` user, in which case you'd just have to create the database and `hive` user separately upstream.

I might be missing something, but I'm not really concerned about SSH, as you can control SSH access via SSH metadata keys or OS Login on your compute instances.

However, I'm concerned about the fact that the initialization action's log is stored in the staging bucket, and that the log displays the passwords in clear. For example, here's a snippet of what appears in the log:

```
...
++ gsutil cat gs://[PROJECT]/hive-password.encrypted
++ gcloud kms decrypt --ciphertext-file - --plaintext-file - --key projects/[PROJECT]/locations/global/keyRings/my-key-ring/cryptoKeys/my-key
+ readonly db_hive_password=hive123
+ db_hive_password=hive123
...
```

The problem is that to allow a user to run jobs via the Dataproc jobs API, you need to give them the `storage.objectViewer` role on the staging bucket (as explained [here](https://cloud.google.com/dataproc/docs/concepts/iam/granular-iam#submitting_jobs_with_granular_iam)), which means that the user can also view the initialization action log with the password displayed in clear.

This issue would still occur with the status quo (i.e. hardcoding the password in the init action), so the KMS approach would not be a regression. But really I'm not sure that this problem can be addressed unless the logging can be changed to **_not_** display the value of variables. Do you know if that can be done?

So anyways, this is an issue that might be OK to live with. You'd just have to clearly spell out the caveat that whoever is allowed to run jobs on the cluster would also have to be trusted at least with the `hive` MySQL user's password.

Any thoughts?

**Comment by karth295** [comment]
Hiding the password is easy -- you can just do something like

```
set +x # Disable printing each command
... commands that contain password ...
set -x # Enable printing each command
```

https://stackoverflow.com/questions/36273665/what-does-set-x-do.

And that makes sense anyway because logs shouldn't contain sensitive information.

But again, since users with access to the jobs API can run arbitrary code on the cluster as root, they'll be able to discover the `hive` password by looking at command line arguments to cloud-sql-proxy by running `ps`. So yeah, that caveat should still be in the README.

**Comment by jphalip** [comment]
@karth295 I've submitted a patch in #260. Let me know what you think!
