### ISSUE TITLE
driver and worker Python versions are incompatible after fresh install

### ISSUE THREAD

**Issue by odedbadt** [GoogleCloudPlatform/dataproc-initialization-actions#310]
worker is installed with 3.6, driver with 3.7

The reason is that after miniconda is installed with python3.6,  conda installs jupyter whihc in turn upgrades python to latest (in my case 3.7

solved it, for the time being by downgrading to python 3.6.6 but not sure how thi coul be solved in a more forward compatible way

**Comment by karth295** [comment]
Yeah, check out the discussion in #300 . I created PR #306, which installs python dependencies on all nodes, rather than just the master. That ensures that even if a package makes conda upgrade python, it upgrades on all nodes.

However, @pmkc convinced me (offline) to close that one and instead just pin to the version of python that comes with the version of Miniconda installed. E.g. something like `conda install jupyter python==$(python --version)`.

**Comment by karth295** [comment]
Closing as a dup.
