### ISSUE TITLE
launch-jupyter-interface.sh error

### ISSUE THREAD

**Issue by Gibbsdavidl** [GoogleCloudPlatform/dataproc-initialization-actions#361]
Hi there,

Having trouble connecting to a Jupyter notebook.  Error below.

bash-3.2$ ./dataproc-initialization-actions/jupyter/launch-jupyter-interface.sh -c=isb-dataproc-cluster -z=us-west1-b
Using following cluster name: my-dataproc-cluster
Using following cluster zone: us-west1-b
Using following remote dataproc jupyter port: 8124

./dataproc-initialization-actions/jupyter/launch-jupyter-interface.sh: line 75: conditional binary operator expected

Please let me know if you need anything,
Thank you!
-dave

**Comment by karth295** [comment]
It looks like you're using bash 3.2, while I'm on bash 4.4, and that particular line works for me. Either way, you can just remove the `[[-v ZONE]]` part, since zone is a required argument for now.

I do plan to clean up this script -- infer the jupyter port without needing to specify one, infer the zone, make it work out of the box on non-Mac machines, etc. I'll close this one in favor of #275 .

If you want to submit a PR for this fix and/or improve anything else, I'd be happy to merge it!
