### ISSUE TITLE
Configure region for master-post-init.sh 

### ISSUE THREAD

**Issue by harveyxia** [GoogleCloudPlatform/dataproc-initialization-actions#445]
Currently the [master-post-init.sh](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/post-init/master-post-init.sh#L47) script fails on this command for clusters whose region is not "global". Can we parameterize the region for this script?

**Comment by karth295** [comment]
I'm actually tempted to delete that init action, since it was sort of a temporary solution to creating a cluster, running a job, then deleting the cluster.

Generally, we recommend creating and using Dataproc workflow templates: https://cloud.google.com/dataproc/docs/concepts/workflows/using-workflows. Workflows allow you to specify the configuration for a cluster and any job(s) in a single yaml file.

For more complex scheduling (e.g. time based, based on when data arrives, etc), consider Cloud Composer (managed Apache Airflow): https://cloud.google.com/composer/.

That being said, feel free to send a pull request and reopen this issue if you still want this feature.
