### ISSUE TITLE
Unable to disable use-cloud-sql-private-ip option

### ISSUE THREAD

**Issue by Obdolbacca** [GoogleCloudPlatform/dataproc-initialization-actions#501]
The check is 
```bash
readonly use_cloud_sql_private_ip="$(/usr/share/google/get_metadata_value attributes/use-cloud-sql-private-ip || true)
```
It can never be false

**Comment by dennishuo** [comment]
To clarify, the script syntax was unfortunately very confusing which is why it wasn't clear what actually happened here.

The "|| true" actually just sets the variable to empty string by default, which then gets interpreted as "false" later, so actually the flag was always "false" by default. Providing any non-empty string as metadata would then cause it to be "true".

As a result, the commit associated with this issue was a breaking change which modified the "default" to actually be "true" for using private-ip. This followup commit preserves the prior behavior of defaulting to "false" once again: https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/504

In this case, I'm curious whether this issue was driven by trying to pass the actual string "false" to the metadata variable?

**Comment by Obdolbacca** [comment]
Yeah, you are right. Any non-empty string is considered as true

пт, 12 апр. 2019 г., 4:35 Dennis Huo <notifications@github.com>:
