### ISSUE TITLE
Running Jupyter as root causes potential security issues

### ISSUE THREAD

**Issue by yu-iskw** [GoogleCloudPlatform/dataproc-initialization-actions#578]
## Overview
The initialization scripts allows users to run jupyter as root. Some of data scientists/machine learning guys tend not to be familiar with security. It would be great to turn off root user in jupyter by default. 

### jupyter
- https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/jupyter/internal/launch-jupyter-kernel.sh#L18
### jupyter2
- https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/jupyter2/jupyter2.sh#L47
- https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/jupyter2/jupyter2.sh#L55

**Comment by karth295** [comment]
In general, we recommend using single-tenant clusters (one cluster per data scientist). Unless you are using [OS Login](https://cloud.google.com/compute/docs/instances/managing-instance-access), any user can just type `sudo` to become root on the cluster, so Linux permissions are generally unimportant.

Most Dataproc users have their data in GCP services, such as Cloud Storage, which are protected via IAM permissions, rather than Linux permissions. And by default, we even store the Jupyter notebooks in GCS.

In a GCE VM, GCP client libraries use the [GCE VM's service account](https://cloud.google.com/compute/docs/access/service-accounts) for accessing GCP services. We recommend creating one service account per user or per team, and then [using](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/service-accounts) the appropriate service account for each ephemeral, single-tenant cluster.

P.S. We're going to make this single-tenant experience more smooth by launching a [Jupyterhub](https://jupyterhub.readthedocs.io/en/stable/) [Spawner](https://jupyterhub.readthedocs.io/en/stable/reference/spawners.html) plugin in a few weeks. The spawner will let you create per-user clusters on demand, and tear them down when idle.

Can you tell us a little more about your use case?
